# Generated by Django 4.2.5 on 2023-09-15 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_subcategory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='Home.category'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='related_category',
        ),
        migrations.AddField(
            model_name='product',
            name='related_category',
            field=models.ManyToManyField(related_name='products', to='Home.category'),
        ),
    ]
